/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * NeuroFlow OS API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  status: zod.string(),
});

/**
 * @summary List all sessions (most recent first)
 */
export const listSessionsQueryLimitDefault = 20;
export const listSessionsQueryOffsetDefault = 0;

export const ListSessionsQueryParams = zod.object({
  limit: zod.coerce.number().default(listSessionsQueryLimitDefault),
  offset: zod.coerce.number().default(listSessionsQueryOffsetDefault),
});

export const listSessionsResponseSnapshotCountDefault = 0;

export const ListSessionsResponseItem = zod.object({
  id: zod.number(),
  label: zod.string().nullish(),
  status: zod.enum(["active", "completed", "paused"]),
  startedAt: zod.coerce.date(),
  endedAt: zod.coerce.date().nullish(),
  durationMinutes: zod.number().nullish(),
  focusScore: zod.number().describe("0-100 average focus score for session"),
  fatigueIndex: zod.number().describe("0-100 fatigue index"),
  distractionRisk: zod.number().describe("0-100 distraction risk"),
  typingWpm: zod.number().nullish().describe("Average typing speed in WPM"),
  pauseRate: zod.number().nullish().describe("Average pause frequency"),
  backspaceRate: zod.number().nullish(),
  snapshotCount: zod.number().default(listSessionsResponseSnapshotCountDefault),
});
export const ListSessionsResponse = zod.array(ListSessionsResponseItem);

/**
 * @summary Start a new focus session
 */
export const CreateSessionBody = zod.object({
  label: zod.string().optional(),
});

/**
 * @summary Get the currently active session (if any)
 */
export const getActiveSessionResponseSnapshotCountDefault = 0;

export const GetActiveSessionResponse = zod.object({
  id: zod.number(),
  label: zod.string().nullish(),
  status: zod.enum(["active", "completed", "paused"]),
  startedAt: zod.coerce.date(),
  endedAt: zod.coerce.date().nullish(),
  durationMinutes: zod.number().nullish(),
  focusScore: zod.number().describe("0-100 average focus score for session"),
  fatigueIndex: zod.number().describe("0-100 fatigue index"),
  distractionRisk: zod.number().describe("0-100 distraction risk"),
  typingWpm: zod.number().nullish().describe("Average typing speed in WPM"),
  pauseRate: zod.number().nullish().describe("Average pause frequency"),
  backspaceRate: zod.number().nullish(),
  snapshotCount: zod
    .number()
    .default(getActiveSessionResponseSnapshotCountDefault),
});

/**
 * @summary Get a session by ID
 */
export const GetSessionParams = zod.object({
  id: zod.coerce.number(),
});

export const getSessionResponseSnapshotCountDefault = 0;

export const GetSessionResponse = zod.object({
  id: zod.number(),
  label: zod.string().nullish(),
  status: zod.enum(["active", "completed", "paused"]),
  startedAt: zod.coerce.date(),
  endedAt: zod.coerce.date().nullish(),
  durationMinutes: zod.number().nullish(),
  focusScore: zod.number().describe("0-100 average focus score for session"),
  fatigueIndex: zod.number().describe("0-100 fatigue index"),
  distractionRisk: zod.number().describe("0-100 distraction risk"),
  typingWpm: zod.number().nullish().describe("Average typing speed in WPM"),
  pauseRate: zod.number().nullish().describe("Average pause frequency"),
  backspaceRate: zod.number().nullish(),
  snapshotCount: zod.number().default(getSessionResponseSnapshotCountDefault),
});

/**
 * @summary Update a session (e.g., stop it)
 */
export const UpdateSessionParams = zod.object({
  id: zod.coerce.number(),
});

export const UpdateSessionBody = zod.object({
  status: zod.enum(["completed", "paused", "active"]).optional(),
  label: zod.string().optional(),
});

export const updateSessionResponseSnapshotCountDefault = 0;

export const UpdateSessionResponse = zod.object({
  id: zod.number(),
  label: zod.string().nullish(),
  status: zod.enum(["active", "completed", "paused"]),
  startedAt: zod.coerce.date(),
  endedAt: zod.coerce.date().nullish(),
  durationMinutes: zod.number().nullish(),
  focusScore: zod.number().describe("0-100 average focus score for session"),
  fatigueIndex: zod.number().describe("0-100 fatigue index"),
  distractionRisk: zod.number().describe("0-100 distraction risk"),
  typingWpm: zod.number().nullish().describe("Average typing speed in WPM"),
  pauseRate: zod.number().nullish().describe("Average pause frequency"),
  backspaceRate: zod.number().nullish(),
  snapshotCount: zod
    .number()
    .default(updateSessionResponseSnapshotCountDefault),
});

/**
 * @summary Get behavioral snapshots for a session
 */
export const ListSessionSnapshotsParams = zod.object({
  id: zod.coerce.number(),
});

export const ListSessionSnapshotsResponseItem = zod.object({
  id: zod.number(),
  sessionId: zod.number(),
  capturedAt: zod.coerce.date(),
  typingWpm: zod.number(),
  pauseCount: zod.number(),
  pauseDurationMs: zod.number().optional(),
  backspaceRate: zod.number(),
  keystrokeCount: zod.number().optional(),
  idleTimeMs: zod.number().optional(),
  focusScore: zod.number(),
  fatigueIndex: zod.number(),
  distractionRisk: zod.number(),
});
export const ListSessionSnapshotsResponse = zod.array(
  ListSessionSnapshotsResponseItem,
);

/**
 * @summary Submit a behavioral snapshot (typing metrics, pauses, etc.)
 */
export const SubmitSnapshotBody = zod.object({
  sessionId: zod.number(),
  typingWpm: zod.number(),
  pauseCount: zod.number(),
  pauseDurationMs: zod.number().optional(),
  backspaceRate: zod.number(),
  keystrokeCount: zod.number(),
  idleTimeMs: zod.number().optional(),
});

/**
 * @summary Get the latest cognitive state prediction
 */
export const GetCurrentPredictionResponse = zod.object({
  id: zod.number(),
  sessionId: zod.number(),
  predictedAt: zod.coerce.date(),
  focusScore: zod.number().describe("Current focus score 0-100"),
  fatigueIndex: zod.number().describe("Fatigue level 0-100"),
  distractionRisk: zod.number().describe("Distraction risk 0-100"),
  focusTrend: zod.enum(["rising", "stable", "declining", "critical"]),
  minutesUntilFocusDrop: zod
    .number()
    .nullish()
    .describe("Predicted minutes until focus drop (null if stable)"),
  alertLevel: zod
    .enum(["none", "low", "medium", "high", "critical"])
    .optional(),
});

/**
 * @summary Get prediction history for the active or recent session
 */
export const listPredictionsQueryLimitDefault = 60;

export const ListPredictionsQueryParams = zod.object({
  sessionId: zod.coerce.number().optional(),
  limit: zod.coerce.number().default(listPredictionsQueryLimitDefault),
});

export const ListPredictionsResponseItem = zod.object({
  id: zod.number(),
  sessionId: zod.number(),
  predictedAt: zod.coerce.date(),
  focusScore: zod.number().describe("Current focus score 0-100"),
  fatigueIndex: zod.number().describe("Fatigue level 0-100"),
  distractionRisk: zod.number().describe("Distraction risk 0-100"),
  focusTrend: zod.enum(["rising", "stable", "declining", "critical"]),
  minutesUntilFocusDrop: zod
    .number()
    .nullish()
    .describe("Predicted minutes until focus drop (null if stable)"),
  alertLevel: zod
    .enum(["none", "low", "medium", "high", "critical"])
    .optional(),
});
export const ListPredictionsResponse = zod.array(ListPredictionsResponseItem);

/**
 * @summary Get list of recent interventions
 */
export const listInterventionsQueryLimitDefault = 10;

export const ListInterventionsQueryParams = zod.object({
  sessionId: zod.coerce.number().optional(),
  limit: zod.coerce.number().default(listInterventionsQueryLimitDefault),
});

export const ListInterventionsResponseItem = zod.object({
  id: zod.number(),
  sessionId: zod.number(),
  type: zod.enum([
    "break_suggestion",
    "focus_mode",
    "reduce_noise",
    "warning",
    "encouragement",
  ]),
  message: zod.string(),
  triggeredAt: zod.coerce.date(),
  acknowledged: zod.boolean(),
  acknowledgedAt: zod.coerce.date().nullish(),
});
export const ListInterventionsResponse = zod.array(
  ListInterventionsResponseItem,
);

/**
 * @summary Acknowledge / dismiss an intervention
 */
export const AcknowledgeInterventionParams = zod.object({
  id: zod.coerce.number(),
});

export const AcknowledgeInterventionResponse = zod.object({
  id: zod.number(),
  sessionId: zod.number(),
  type: zod.enum([
    "break_suggestion",
    "focus_mode",
    "reduce_noise",
    "warning",
    "encouragement",
  ]),
  message: zod.string(),
  triggeredAt: zod.coerce.date(),
  acknowledged: zod.boolean(),
  acknowledgedAt: zod.coerce.date().nullish(),
});

/**
 * @summary Get AI-generated cognitive insights
 */
export const ListInsightsResponseItem = zod.object({
  id: zod.number(),
  category: zod.enum([
    "peak_hours",
    "session_length",
    "break_pattern",
    "fatigue_pattern",
    "focus_pattern",
  ]),
  text: zod.string().describe("Human-readable insight"),
  confidence: zod.number().describe("0-1 confidence score"),
  dataPoints: zod.number().optional().describe("Number of data points used"),
  generatedAt: zod.coerce.date(),
});
export const ListInsightsResponse = zod.array(ListInsightsResponseItem);

/**
 * @summary Get the user's cognitive profile
 */
export const GetProfileResponse = zod.object({
  id: zod.number(),
  peakFocusHourStart: zod.number().describe("Hour of day (0-23)"),
  peakFocusHourEnd: zod.number(),
  avgAttentionSpanMinutes: zod.number(),
  fatigueThreshold: zod.number().describe("WPM drop % that indicates fatigue"),
  baselineWpm: zod.number().nullish(),
  baselinePauseRate: zod.number().nullish(),
  totalSessions: zod.number(),
  totalFocusMinutes: zod.number(),
  updatedAt: zod.coerce.date().optional(),
});

/**
 * @summary Update user cognitive profile settings
 */
export const UpdateProfileBody = zod.object({
  peakFocusHourStart: zod.number().optional(),
  peakFocusHourEnd: zod.number().optional(),
  avgAttentionSpanMinutes: zod.number().optional(),
  fatigueThreshold: zod.number().optional(),
});

export const UpdateProfileResponse = zod.object({
  id: zod.number(),
  peakFocusHourStart: zod.number().describe("Hour of day (0-23)"),
  peakFocusHourEnd: zod.number(),
  avgAttentionSpanMinutes: zod.number(),
  fatigueThreshold: zod.number().describe("WPM drop % that indicates fatigue"),
  baselineWpm: zod.number().nullish(),
  baselinePauseRate: zod.number().nullish(),
  totalSessions: zod.number(),
  totalFocusMinutes: zod.number(),
  updatedAt: zod.coerce.date().optional(),
});

/**
 * @summary Get dashboard summary (total sessions, avg focus, top hours, etc.)
 */
export const GetDashboardSummaryResponse = zod.object({
  totalSessions: zod.number(),
  completedSessions: zod.number(),
  totalFocusMinutes: zod.number(),
  avgFocusScore: zod.number(),
  avgFatigueIndex: zod.number(),
  avgDistractionRisk: zod.number(),
  streakDays: zod.number(),
  todaySessions: zod.number(),
  todayFocusMinutes: zod.number(),
  bestFocusHour: zod.number().nullish(),
  totalInterventions: zod.number().optional(),
});

/**
 * @summary Get productivity trend over recent sessions
 */
export const getProductivityTrendQueryDaysDefault = 7;

export const GetProductivityTrendQueryParams = zod.object({
  days: zod.coerce.number().default(getProductivityTrendQueryDaysDefault),
});

export const GetProductivityTrendResponseItem = zod.object({
  date: zod.coerce.date(),
  avgFocusScore: zod.number(),
  avgFatigueIndex: zod.number(),
  sessionCount: zod.number(),
  totalMinutes: zod.number(),
});
export const GetProductivityTrendResponse = zod.array(
  GetProductivityTrendResponseItem,
);

/**
 * @summary Get peak focus hours breakdown
 */
export const GetPeakHoursResponseItem = zod.object({
  hour: zod.number().describe("Hour of day 0-23"),
  avgFocusScore: zod.number(),
  sessionCount: zod.number(),
});
export const GetPeakHoursResponse = zod.array(GetPeakHoursResponseItem);
