/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * NeuroFlow OS API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";
/**
 * @summary Health check
 */
export declare const HealthCheckResponse: zod.ZodObject<{
    status: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: string;
}, {
    status: string;
}>;
/**
 * @summary List all sessions (most recent first)
 */
export declare const listSessionsQueryLimitDefault = 20;
export declare const listSessionsQueryOffsetDefault = 0;
export declare const ListSessionsQueryParams: zod.ZodObject<{
    limit: zod.ZodDefault<zod.ZodNumber>;
    offset: zod.ZodDefault<zod.ZodNumber>;
}, "strip", zod.ZodTypeAny, {
    limit: number;
    offset: number;
}, {
    limit?: number | undefined;
    offset?: number | undefined;
}>;
export declare const listSessionsResponseSnapshotCountDefault = 0;
export declare const ListSessionsResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    label: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    status: zod.ZodEnum<["active", "completed", "paused"]>;
    startedAt: zod.ZodDate;
    endedAt: zod.ZodOptional<zod.ZodNullable<zod.ZodDate>>;
    durationMinutes: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    focusScore: zod.ZodNumber;
    fatigueIndex: zod.ZodNumber;
    distractionRisk: zod.ZodNumber;
    typingWpm: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    pauseRate: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    backspaceRate: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    snapshotCount: zod.ZodDefault<zod.ZodNumber>;
}, "strip", zod.ZodTypeAny, {
    status: "active" | "completed" | "paused";
    id: number;
    startedAt: Date;
    focusScore: number;
    fatigueIndex: number;
    distractionRisk: number;
    snapshotCount: number;
    label?: string | null | undefined;
    endedAt?: Date | null | undefined;
    durationMinutes?: number | null | undefined;
    typingWpm?: number | null | undefined;
    pauseRate?: number | null | undefined;
    backspaceRate?: number | null | undefined;
}, {
    status: "active" | "completed" | "paused";
    id: number;
    startedAt: Date;
    focusScore: number;
    fatigueIndex: number;
    distractionRisk: number;
    label?: string | null | undefined;
    endedAt?: Date | null | undefined;
    durationMinutes?: number | null | undefined;
    typingWpm?: number | null | undefined;
    pauseRate?: number | null | undefined;
    backspaceRate?: number | null | undefined;
    snapshotCount?: number | undefined;
}>;
export declare const ListSessionsResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    label: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    status: zod.ZodEnum<["active", "completed", "paused"]>;
    startedAt: zod.ZodDate;
    endedAt: zod.ZodOptional<zod.ZodNullable<zod.ZodDate>>;
    durationMinutes: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    focusScore: zod.ZodNumber;
    fatigueIndex: zod.ZodNumber;
    distractionRisk: zod.ZodNumber;
    typingWpm: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    pauseRate: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    backspaceRate: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    snapshotCount: zod.ZodDefault<zod.ZodNumber>;
}, "strip", zod.ZodTypeAny, {
    status: "active" | "completed" | "paused";
    id: number;
    startedAt: Date;
    focusScore: number;
    fatigueIndex: number;
    distractionRisk: number;
    snapshotCount: number;
    label?: string | null | undefined;
    endedAt?: Date | null | undefined;
    durationMinutes?: number | null | undefined;
    typingWpm?: number | null | undefined;
    pauseRate?: number | null | undefined;
    backspaceRate?: number | null | undefined;
}, {
    status: "active" | "completed" | "paused";
    id: number;
    startedAt: Date;
    focusScore: number;
    fatigueIndex: number;
    distractionRisk: number;
    label?: string | null | undefined;
    endedAt?: Date | null | undefined;
    durationMinutes?: number | null | undefined;
    typingWpm?: number | null | undefined;
    pauseRate?: number | null | undefined;
    backspaceRate?: number | null | undefined;
    snapshotCount?: number | undefined;
}>, "many">;
/**
 * @summary Start a new focus session
 */
export declare const CreateSessionBody: zod.ZodObject<{
    label: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    label?: string | undefined;
}, {
    label?: string | undefined;
}>;
/**
 * @summary Get the currently active session (if any)
 */
export declare const getActiveSessionResponseSnapshotCountDefault = 0;
export declare const GetActiveSessionResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    label: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    status: zod.ZodEnum<["active", "completed", "paused"]>;
    startedAt: zod.ZodDate;
    endedAt: zod.ZodOptional<zod.ZodNullable<zod.ZodDate>>;
    durationMinutes: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    focusScore: zod.ZodNumber;
    fatigueIndex: zod.ZodNumber;
    distractionRisk: zod.ZodNumber;
    typingWpm: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    pauseRate: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    backspaceRate: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    snapshotCount: zod.ZodDefault<zod.ZodNumber>;
}, "strip", zod.ZodTypeAny, {
    status: "active" | "completed" | "paused";
    id: number;
    startedAt: Date;
    focusScore: number;
    fatigueIndex: number;
    distractionRisk: number;
    snapshotCount: number;
    label?: string | null | undefined;
    endedAt?: Date | null | undefined;
    durationMinutes?: number | null | undefined;
    typingWpm?: number | null | undefined;
    pauseRate?: number | null | undefined;
    backspaceRate?: number | null | undefined;
}, {
    status: "active" | "completed" | "paused";
    id: number;
    startedAt: Date;
    focusScore: number;
    fatigueIndex: number;
    distractionRisk: number;
    label?: string | null | undefined;
    endedAt?: Date | null | undefined;
    durationMinutes?: number | null | undefined;
    typingWpm?: number | null | undefined;
    pauseRate?: number | null | undefined;
    backspaceRate?: number | null | undefined;
    snapshotCount?: number | undefined;
}>;
/**
 * @summary Get a session by ID
 */
export declare const GetSessionParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const getSessionResponseSnapshotCountDefault = 0;
export declare const GetSessionResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    label: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    status: zod.ZodEnum<["active", "completed", "paused"]>;
    startedAt: zod.ZodDate;
    endedAt: zod.ZodOptional<zod.ZodNullable<zod.ZodDate>>;
    durationMinutes: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    focusScore: zod.ZodNumber;
    fatigueIndex: zod.ZodNumber;
    distractionRisk: zod.ZodNumber;
    typingWpm: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    pauseRate: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    backspaceRate: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    snapshotCount: zod.ZodDefault<zod.ZodNumber>;
}, "strip", zod.ZodTypeAny, {
    status: "active" | "completed" | "paused";
    id: number;
    startedAt: Date;
    focusScore: number;
    fatigueIndex: number;
    distractionRisk: number;
    snapshotCount: number;
    label?: string | null | undefined;
    endedAt?: Date | null | undefined;
    durationMinutes?: number | null | undefined;
    typingWpm?: number | null | undefined;
    pauseRate?: number | null | undefined;
    backspaceRate?: number | null | undefined;
}, {
    status: "active" | "completed" | "paused";
    id: number;
    startedAt: Date;
    focusScore: number;
    fatigueIndex: number;
    distractionRisk: number;
    label?: string | null | undefined;
    endedAt?: Date | null | undefined;
    durationMinutes?: number | null | undefined;
    typingWpm?: number | null | undefined;
    pauseRate?: number | null | undefined;
    backspaceRate?: number | null | undefined;
    snapshotCount?: number | undefined;
}>;
/**
 * @summary Update a session (e.g., stop it)
 */
export declare const UpdateSessionParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const UpdateSessionBody: zod.ZodObject<{
    status: zod.ZodOptional<zod.ZodEnum<["completed", "paused", "active"]>>;
    label: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    status?: "active" | "completed" | "paused" | undefined;
    label?: string | undefined;
}, {
    status?: "active" | "completed" | "paused" | undefined;
    label?: string | undefined;
}>;
export declare const updateSessionResponseSnapshotCountDefault = 0;
export declare const UpdateSessionResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    label: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    status: zod.ZodEnum<["active", "completed", "paused"]>;
    startedAt: zod.ZodDate;
    endedAt: zod.ZodOptional<zod.ZodNullable<zod.ZodDate>>;
    durationMinutes: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    focusScore: zod.ZodNumber;
    fatigueIndex: zod.ZodNumber;
    distractionRisk: zod.ZodNumber;
    typingWpm: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    pauseRate: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    backspaceRate: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    snapshotCount: zod.ZodDefault<zod.ZodNumber>;
}, "strip", zod.ZodTypeAny, {
    status: "active" | "completed" | "paused";
    id: number;
    startedAt: Date;
    focusScore: number;
    fatigueIndex: number;
    distractionRisk: number;
    snapshotCount: number;
    label?: string | null | undefined;
    endedAt?: Date | null | undefined;
    durationMinutes?: number | null | undefined;
    typingWpm?: number | null | undefined;
    pauseRate?: number | null | undefined;
    backspaceRate?: number | null | undefined;
}, {
    status: "active" | "completed" | "paused";
    id: number;
    startedAt: Date;
    focusScore: number;
    fatigueIndex: number;
    distractionRisk: number;
    label?: string | null | undefined;
    endedAt?: Date | null | undefined;
    durationMinutes?: number | null | undefined;
    typingWpm?: number | null | undefined;
    pauseRate?: number | null | undefined;
    backspaceRate?: number | null | undefined;
    snapshotCount?: number | undefined;
}>;
/**
 * @summary Get behavioral snapshots for a session
 */
export declare const ListSessionSnapshotsParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const ListSessionSnapshotsResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    sessionId: zod.ZodNumber;
    capturedAt: zod.ZodDate;
    typingWpm: zod.ZodNumber;
    pauseCount: zod.ZodNumber;
    pauseDurationMs: zod.ZodOptional<zod.ZodNumber>;
    backspaceRate: zod.ZodNumber;
    keystrokeCount: zod.ZodOptional<zod.ZodNumber>;
    idleTimeMs: zod.ZodOptional<zod.ZodNumber>;
    focusScore: zod.ZodNumber;
    fatigueIndex: zod.ZodNumber;
    distractionRisk: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
    focusScore: number;
    fatigueIndex: number;
    distractionRisk: number;
    typingWpm: number;
    backspaceRate: number;
    sessionId: number;
    capturedAt: Date;
    pauseCount: number;
    pauseDurationMs?: number | undefined;
    keystrokeCount?: number | undefined;
    idleTimeMs?: number | undefined;
}, {
    id: number;
    focusScore: number;
    fatigueIndex: number;
    distractionRisk: number;
    typingWpm: number;
    backspaceRate: number;
    sessionId: number;
    capturedAt: Date;
    pauseCount: number;
    pauseDurationMs?: number | undefined;
    keystrokeCount?: number | undefined;
    idleTimeMs?: number | undefined;
}>;
export declare const ListSessionSnapshotsResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    sessionId: zod.ZodNumber;
    capturedAt: zod.ZodDate;
    typingWpm: zod.ZodNumber;
    pauseCount: zod.ZodNumber;
    pauseDurationMs: zod.ZodOptional<zod.ZodNumber>;
    backspaceRate: zod.ZodNumber;
    keystrokeCount: zod.ZodOptional<zod.ZodNumber>;
    idleTimeMs: zod.ZodOptional<zod.ZodNumber>;
    focusScore: zod.ZodNumber;
    fatigueIndex: zod.ZodNumber;
    distractionRisk: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
    focusScore: number;
    fatigueIndex: number;
    distractionRisk: number;
    typingWpm: number;
    backspaceRate: number;
    sessionId: number;
    capturedAt: Date;
    pauseCount: number;
    pauseDurationMs?: number | undefined;
    keystrokeCount?: number | undefined;
    idleTimeMs?: number | undefined;
}, {
    id: number;
    focusScore: number;
    fatigueIndex: number;
    distractionRisk: number;
    typingWpm: number;
    backspaceRate: number;
    sessionId: number;
    capturedAt: Date;
    pauseCount: number;
    pauseDurationMs?: number | undefined;
    keystrokeCount?: number | undefined;
    idleTimeMs?: number | undefined;
}>, "many">;
/**
 * @summary Submit a behavioral snapshot (typing metrics, pauses, etc.)
 */
export declare const SubmitSnapshotBody: zod.ZodObject<{
    sessionId: zod.ZodNumber;
    typingWpm: zod.ZodNumber;
    pauseCount: zod.ZodNumber;
    pauseDurationMs: zod.ZodOptional<zod.ZodNumber>;
    backspaceRate: zod.ZodNumber;
    keystrokeCount: zod.ZodNumber;
    idleTimeMs: zod.ZodOptional<zod.ZodNumber>;
}, "strip", zod.ZodTypeAny, {
    typingWpm: number;
    backspaceRate: number;
    sessionId: number;
    pauseCount: number;
    keystrokeCount: number;
    pauseDurationMs?: number | undefined;
    idleTimeMs?: number | undefined;
}, {
    typingWpm: number;
    backspaceRate: number;
    sessionId: number;
    pauseCount: number;
    keystrokeCount: number;
    pauseDurationMs?: number | undefined;
    idleTimeMs?: number | undefined;
}>;
/**
 * @summary Get the latest cognitive state prediction
 */
export declare const GetCurrentPredictionResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    sessionId: zod.ZodNumber;
    predictedAt: zod.ZodDate;
    focusScore: zod.ZodNumber;
    fatigueIndex: zod.ZodNumber;
    distractionRisk: zod.ZodNumber;
    focusTrend: zod.ZodEnum<["rising", "stable", "declining", "critical"]>;
    minutesUntilFocusDrop: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    alertLevel: zod.ZodOptional<zod.ZodEnum<["none", "low", "medium", "high", "critical"]>>;
}, "strip", zod.ZodTypeAny, {
    id: number;
    focusScore: number;
    fatigueIndex: number;
    distractionRisk: number;
    sessionId: number;
    predictedAt: Date;
    focusTrend: "rising" | "stable" | "declining" | "critical";
    minutesUntilFocusDrop?: number | null | undefined;
    alertLevel?: "critical" | "none" | "low" | "medium" | "high" | undefined;
}, {
    id: number;
    focusScore: number;
    fatigueIndex: number;
    distractionRisk: number;
    sessionId: number;
    predictedAt: Date;
    focusTrend: "rising" | "stable" | "declining" | "critical";
    minutesUntilFocusDrop?: number | null | undefined;
    alertLevel?: "critical" | "none" | "low" | "medium" | "high" | undefined;
}>;
/**
 * @summary Get prediction history for the active or recent session
 */
export declare const listPredictionsQueryLimitDefault = 60;
export declare const ListPredictionsQueryParams: zod.ZodObject<{
    sessionId: zod.ZodOptional<zod.ZodNumber>;
    limit: zod.ZodDefault<zod.ZodNumber>;
}, "strip", zod.ZodTypeAny, {
    limit: number;
    sessionId?: number | undefined;
}, {
    limit?: number | undefined;
    sessionId?: number | undefined;
}>;
export declare const ListPredictionsResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    sessionId: zod.ZodNumber;
    predictedAt: zod.ZodDate;
    focusScore: zod.ZodNumber;
    fatigueIndex: zod.ZodNumber;
    distractionRisk: zod.ZodNumber;
    focusTrend: zod.ZodEnum<["rising", "stable", "declining", "critical"]>;
    minutesUntilFocusDrop: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    alertLevel: zod.ZodOptional<zod.ZodEnum<["none", "low", "medium", "high", "critical"]>>;
}, "strip", zod.ZodTypeAny, {
    id: number;
    focusScore: number;
    fatigueIndex: number;
    distractionRisk: number;
    sessionId: number;
    predictedAt: Date;
    focusTrend: "rising" | "stable" | "declining" | "critical";
    minutesUntilFocusDrop?: number | null | undefined;
    alertLevel?: "critical" | "none" | "low" | "medium" | "high" | undefined;
}, {
    id: number;
    focusScore: number;
    fatigueIndex: number;
    distractionRisk: number;
    sessionId: number;
    predictedAt: Date;
    focusTrend: "rising" | "stable" | "declining" | "critical";
    minutesUntilFocusDrop?: number | null | undefined;
    alertLevel?: "critical" | "none" | "low" | "medium" | "high" | undefined;
}>;
export declare const ListPredictionsResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    sessionId: zod.ZodNumber;
    predictedAt: zod.ZodDate;
    focusScore: zod.ZodNumber;
    fatigueIndex: zod.ZodNumber;
    distractionRisk: zod.ZodNumber;
    focusTrend: zod.ZodEnum<["rising", "stable", "declining", "critical"]>;
    minutesUntilFocusDrop: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    alertLevel: zod.ZodOptional<zod.ZodEnum<["none", "low", "medium", "high", "critical"]>>;
}, "strip", zod.ZodTypeAny, {
    id: number;
    focusScore: number;
    fatigueIndex: number;
    distractionRisk: number;
    sessionId: number;
    predictedAt: Date;
    focusTrend: "rising" | "stable" | "declining" | "critical";
    minutesUntilFocusDrop?: number | null | undefined;
    alertLevel?: "critical" | "none" | "low" | "medium" | "high" | undefined;
}, {
    id: number;
    focusScore: number;
    fatigueIndex: number;
    distractionRisk: number;
    sessionId: number;
    predictedAt: Date;
    focusTrend: "rising" | "stable" | "declining" | "critical";
    minutesUntilFocusDrop?: number | null | undefined;
    alertLevel?: "critical" | "none" | "low" | "medium" | "high" | undefined;
}>, "many">;
/**
 * @summary Get list of recent interventions
 */
export declare const listInterventionsQueryLimitDefault = 10;
export declare const ListInterventionsQueryParams: zod.ZodObject<{
    sessionId: zod.ZodOptional<zod.ZodNumber>;
    limit: zod.ZodDefault<zod.ZodNumber>;
}, "strip", zod.ZodTypeAny, {
    limit: number;
    sessionId?: number | undefined;
}, {
    limit?: number | undefined;
    sessionId?: number | undefined;
}>;
export declare const ListInterventionsResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    sessionId: zod.ZodNumber;
    type: zod.ZodEnum<["break_suggestion", "focus_mode", "reduce_noise", "warning", "encouragement"]>;
    message: zod.ZodString;
    triggeredAt: zod.ZodDate;
    acknowledged: zod.ZodBoolean;
    acknowledgedAt: zod.ZodOptional<zod.ZodNullable<zod.ZodDate>>;
}, "strip", zod.ZodTypeAny, {
    message: string;
    type: "break_suggestion" | "focus_mode" | "reduce_noise" | "warning" | "encouragement";
    id: number;
    sessionId: number;
    triggeredAt: Date;
    acknowledged: boolean;
    acknowledgedAt?: Date | null | undefined;
}, {
    message: string;
    type: "break_suggestion" | "focus_mode" | "reduce_noise" | "warning" | "encouragement";
    id: number;
    sessionId: number;
    triggeredAt: Date;
    acknowledged: boolean;
    acknowledgedAt?: Date | null | undefined;
}>;
export declare const ListInterventionsResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    sessionId: zod.ZodNumber;
    type: zod.ZodEnum<["break_suggestion", "focus_mode", "reduce_noise", "warning", "encouragement"]>;
    message: zod.ZodString;
    triggeredAt: zod.ZodDate;
    acknowledged: zod.ZodBoolean;
    acknowledgedAt: zod.ZodOptional<zod.ZodNullable<zod.ZodDate>>;
}, "strip", zod.ZodTypeAny, {
    message: string;
    type: "break_suggestion" | "focus_mode" | "reduce_noise" | "warning" | "encouragement";
    id: number;
    sessionId: number;
    triggeredAt: Date;
    acknowledged: boolean;
    acknowledgedAt?: Date | null | undefined;
}, {
    message: string;
    type: "break_suggestion" | "focus_mode" | "reduce_noise" | "warning" | "encouragement";
    id: number;
    sessionId: number;
    triggeredAt: Date;
    acknowledged: boolean;
    acknowledgedAt?: Date | null | undefined;
}>, "many">;
/**
 * @summary Acknowledge / dismiss an intervention
 */
export declare const AcknowledgeInterventionParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const AcknowledgeInterventionResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    sessionId: zod.ZodNumber;
    type: zod.ZodEnum<["break_suggestion", "focus_mode", "reduce_noise", "warning", "encouragement"]>;
    message: zod.ZodString;
    triggeredAt: zod.ZodDate;
    acknowledged: zod.ZodBoolean;
    acknowledgedAt: zod.ZodOptional<zod.ZodNullable<zod.ZodDate>>;
}, "strip", zod.ZodTypeAny, {
    message: string;
    type: "break_suggestion" | "focus_mode" | "reduce_noise" | "warning" | "encouragement";
    id: number;
    sessionId: number;
    triggeredAt: Date;
    acknowledged: boolean;
    acknowledgedAt?: Date | null | undefined;
}, {
    message: string;
    type: "break_suggestion" | "focus_mode" | "reduce_noise" | "warning" | "encouragement";
    id: number;
    sessionId: number;
    triggeredAt: Date;
    acknowledged: boolean;
    acknowledgedAt?: Date | null | undefined;
}>;
/**
 * @summary Get AI-generated cognitive insights
 */
export declare const ListInsightsResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    category: zod.ZodEnum<["peak_hours", "session_length", "break_pattern", "fatigue_pattern", "focus_pattern"]>;
    text: zod.ZodString;
    confidence: zod.ZodNumber;
    dataPoints: zod.ZodOptional<zod.ZodNumber>;
    generatedAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: number;
    category: "peak_hours" | "session_length" | "break_pattern" | "fatigue_pattern" | "focus_pattern";
    text: string;
    confidence: number;
    generatedAt: Date;
    dataPoints?: number | undefined;
}, {
    id: number;
    category: "peak_hours" | "session_length" | "break_pattern" | "fatigue_pattern" | "focus_pattern";
    text: string;
    confidence: number;
    generatedAt: Date;
    dataPoints?: number | undefined;
}>;
export declare const ListInsightsResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    category: zod.ZodEnum<["peak_hours", "session_length", "break_pattern", "fatigue_pattern", "focus_pattern"]>;
    text: zod.ZodString;
    confidence: zod.ZodNumber;
    dataPoints: zod.ZodOptional<zod.ZodNumber>;
    generatedAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: number;
    category: "peak_hours" | "session_length" | "break_pattern" | "fatigue_pattern" | "focus_pattern";
    text: string;
    confidence: number;
    generatedAt: Date;
    dataPoints?: number | undefined;
}, {
    id: number;
    category: "peak_hours" | "session_length" | "break_pattern" | "fatigue_pattern" | "focus_pattern";
    text: string;
    confidence: number;
    generatedAt: Date;
    dataPoints?: number | undefined;
}>, "many">;
/**
 * @summary Get the user's cognitive profile
 */
export declare const GetProfileResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    peakFocusHourStart: zod.ZodNumber;
    peakFocusHourEnd: zod.ZodNumber;
    avgAttentionSpanMinutes: zod.ZodNumber;
    fatigueThreshold: zod.ZodNumber;
    baselineWpm: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    baselinePauseRate: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    totalSessions: zod.ZodNumber;
    totalFocusMinutes: zod.ZodNumber;
    updatedAt: zod.ZodOptional<zod.ZodDate>;
}, "strip", zod.ZodTypeAny, {
    id: number;
    peakFocusHourStart: number;
    peakFocusHourEnd: number;
    avgAttentionSpanMinutes: number;
    fatigueThreshold: number;
    totalSessions: number;
    totalFocusMinutes: number;
    baselineWpm?: number | null | undefined;
    baselinePauseRate?: number | null | undefined;
    updatedAt?: Date | undefined;
}, {
    id: number;
    peakFocusHourStart: number;
    peakFocusHourEnd: number;
    avgAttentionSpanMinutes: number;
    fatigueThreshold: number;
    totalSessions: number;
    totalFocusMinutes: number;
    baselineWpm?: number | null | undefined;
    baselinePauseRate?: number | null | undefined;
    updatedAt?: Date | undefined;
}>;
/**
 * @summary Update user cognitive profile settings
 */
export declare const UpdateProfileBody: zod.ZodObject<{
    peakFocusHourStart: zod.ZodOptional<zod.ZodNumber>;
    peakFocusHourEnd: zod.ZodOptional<zod.ZodNumber>;
    avgAttentionSpanMinutes: zod.ZodOptional<zod.ZodNumber>;
    fatigueThreshold: zod.ZodOptional<zod.ZodNumber>;
}, "strip", zod.ZodTypeAny, {
    peakFocusHourStart?: number | undefined;
    peakFocusHourEnd?: number | undefined;
    avgAttentionSpanMinutes?: number | undefined;
    fatigueThreshold?: number | undefined;
}, {
    peakFocusHourStart?: number | undefined;
    peakFocusHourEnd?: number | undefined;
    avgAttentionSpanMinutes?: number | undefined;
    fatigueThreshold?: number | undefined;
}>;
export declare const UpdateProfileResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    peakFocusHourStart: zod.ZodNumber;
    peakFocusHourEnd: zod.ZodNumber;
    avgAttentionSpanMinutes: zod.ZodNumber;
    fatigueThreshold: zod.ZodNumber;
    baselineWpm: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    baselinePauseRate: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    totalSessions: zod.ZodNumber;
    totalFocusMinutes: zod.ZodNumber;
    updatedAt: zod.ZodOptional<zod.ZodDate>;
}, "strip", zod.ZodTypeAny, {
    id: number;
    peakFocusHourStart: number;
    peakFocusHourEnd: number;
    avgAttentionSpanMinutes: number;
    fatigueThreshold: number;
    totalSessions: number;
    totalFocusMinutes: number;
    baselineWpm?: number | null | undefined;
    baselinePauseRate?: number | null | undefined;
    updatedAt?: Date | undefined;
}, {
    id: number;
    peakFocusHourStart: number;
    peakFocusHourEnd: number;
    avgAttentionSpanMinutes: number;
    fatigueThreshold: number;
    totalSessions: number;
    totalFocusMinutes: number;
    baselineWpm?: number | null | undefined;
    baselinePauseRate?: number | null | undefined;
    updatedAt?: Date | undefined;
}>;
/**
 * @summary Get dashboard summary (total sessions, avg focus, top hours, etc.)
 */
export declare const GetDashboardSummaryResponse: zod.ZodObject<{
    totalSessions: zod.ZodNumber;
    completedSessions: zod.ZodNumber;
    totalFocusMinutes: zod.ZodNumber;
    avgFocusScore: zod.ZodNumber;
    avgFatigueIndex: zod.ZodNumber;
    avgDistractionRisk: zod.ZodNumber;
    streakDays: zod.ZodNumber;
    todaySessions: zod.ZodNumber;
    todayFocusMinutes: zod.ZodNumber;
    bestFocusHour: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    totalInterventions: zod.ZodOptional<zod.ZodNumber>;
}, "strip", zod.ZodTypeAny, {
    totalSessions: number;
    totalFocusMinutes: number;
    completedSessions: number;
    avgFocusScore: number;
    avgFatigueIndex: number;
    avgDistractionRisk: number;
    streakDays: number;
    todaySessions: number;
    todayFocusMinutes: number;
    bestFocusHour?: number | null | undefined;
    totalInterventions?: number | undefined;
}, {
    totalSessions: number;
    totalFocusMinutes: number;
    completedSessions: number;
    avgFocusScore: number;
    avgFatigueIndex: number;
    avgDistractionRisk: number;
    streakDays: number;
    todaySessions: number;
    todayFocusMinutes: number;
    bestFocusHour?: number | null | undefined;
    totalInterventions?: number | undefined;
}>;
/**
 * @summary Get productivity trend over recent sessions
 */
export declare const getProductivityTrendQueryDaysDefault = 7;
export declare const GetProductivityTrendQueryParams: zod.ZodObject<{
    days: zod.ZodDefault<zod.ZodNumber>;
}, "strip", zod.ZodTypeAny, {
    days: number;
}, {
    days?: number | undefined;
}>;
export declare const GetProductivityTrendResponseItem: zod.ZodObject<{
    date: zod.ZodDate;
    avgFocusScore: zod.ZodNumber;
    avgFatigueIndex: zod.ZodNumber;
    sessionCount: zod.ZodNumber;
    totalMinutes: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    date: Date;
    avgFocusScore: number;
    avgFatigueIndex: number;
    sessionCount: number;
    totalMinutes: number;
}, {
    date: Date;
    avgFocusScore: number;
    avgFatigueIndex: number;
    sessionCount: number;
    totalMinutes: number;
}>;
export declare const GetProductivityTrendResponse: zod.ZodArray<zod.ZodObject<{
    date: zod.ZodDate;
    avgFocusScore: zod.ZodNumber;
    avgFatigueIndex: zod.ZodNumber;
    sessionCount: zod.ZodNumber;
    totalMinutes: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    date: Date;
    avgFocusScore: number;
    avgFatigueIndex: number;
    sessionCount: number;
    totalMinutes: number;
}, {
    date: Date;
    avgFocusScore: number;
    avgFatigueIndex: number;
    sessionCount: number;
    totalMinutes: number;
}>, "many">;
/**
 * @summary Get peak focus hours breakdown
 */
export declare const GetPeakHoursResponseItem: zod.ZodObject<{
    hour: zod.ZodNumber;
    avgFocusScore: zod.ZodNumber;
    sessionCount: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    avgFocusScore: number;
    sessionCount: number;
    hour: number;
}, {
    avgFocusScore: number;
    sessionCount: number;
    hour: number;
}>;
export declare const GetPeakHoursResponse: zod.ZodArray<zod.ZodObject<{
    hour: zod.ZodNumber;
    avgFocusScore: zod.ZodNumber;
    sessionCount: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    avgFocusScore: number;
    sessionCount: number;
    hour: number;
}, {
    avgFocusScore: number;
    sessionCount: number;
    hour: number;
}>, "many">;
//# sourceMappingURL=api.d.ts.map