/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * NeuroFlow OS API
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export type SessionStatus = (typeof SessionStatus)[keyof typeof SessionStatus];

export const SessionStatus = {
  active: "active",
  completed: "completed",
  paused: "paused",
} as const;

export interface Session {
  id: number;
  /** @nullable */
  label?: string | null;
  status: SessionStatus;
  startedAt: string;
  /** @nullable */
  endedAt?: string | null;
  /** @nullable */
  durationMinutes?: number | null;
  /** 0-100 average focus score for session */
  focusScore: number;
  /** 0-100 fatigue index */
  fatigueIndex: number;
  /** 0-100 distraction risk */
  distractionRisk: number;
  /**
   * Average typing speed in WPM
   * @nullable
   */
  typingWpm?: number | null;
  /**
   * Average pause frequency
   * @nullable
   */
  pauseRate?: number | null;
  /** @nullable */
  backspaceRate?: number | null;
  snapshotCount?: number;
}

export interface SessionInput {
  label?: string;
}

export type SessionUpdateStatus =
  (typeof SessionUpdateStatus)[keyof typeof SessionUpdateStatus];

export const SessionUpdateStatus = {
  completed: "completed",
  paused: "paused",
  active: "active",
} as const;

export interface SessionUpdate {
  status?: SessionUpdateStatus;
  label?: string;
}

export interface BehavioralSnapshot {
  id: number;
  sessionId: number;
  capturedAt: string;
  typingWpm: number;
  pauseCount: number;
  pauseDurationMs?: number;
  backspaceRate: number;
  keystrokeCount?: number;
  idleTimeMs?: number;
  focusScore: number;
  fatigueIndex: number;
  distractionRisk: number;
}

export interface SnapshotInput {
  sessionId: number;
  typingWpm: number;
  pauseCount: number;
  pauseDurationMs?: number;
  backspaceRate: number;
  keystrokeCount: number;
  idleTimeMs?: number;
}

export type PredictionFocusTrend =
  (typeof PredictionFocusTrend)[keyof typeof PredictionFocusTrend];

export const PredictionFocusTrend = {
  rising: "rising",
  stable: "stable",
  declining: "declining",
  critical: "critical",
} as const;

export type PredictionAlertLevel =
  (typeof PredictionAlertLevel)[keyof typeof PredictionAlertLevel];

export const PredictionAlertLevel = {
  none: "none",
  low: "low",
  medium: "medium",
  high: "high",
  critical: "critical",
} as const;

export interface Prediction {
  id: number;
  sessionId: number;
  predictedAt: string;
  /** Current focus score 0-100 */
  focusScore: number;
  /** Fatigue level 0-100 */
  fatigueIndex: number;
  /** Distraction risk 0-100 */
  distractionRisk: number;
  focusTrend: PredictionFocusTrend;
  /**
   * Predicted minutes until focus drop (null if stable)
   * @nullable
   */
  minutesUntilFocusDrop?: number | null;
  alertLevel?: PredictionAlertLevel;
}

export type InterventionType =
  (typeof InterventionType)[keyof typeof InterventionType];

export const InterventionType = {
  break_suggestion: "break_suggestion",
  focus_mode: "focus_mode",
  reduce_noise: "reduce_noise",
  warning: "warning",
  encouragement: "encouragement",
} as const;

export interface Intervention {
  id: number;
  sessionId: number;
  type: InterventionType;
  message: string;
  triggeredAt: string;
  acknowledged: boolean;
  /** @nullable */
  acknowledgedAt?: string | null;
}

export interface SnapshotResult {
  snapshot: BehavioralSnapshot;
  prediction: Prediction;
  intervention?: Intervention;
}

export type InsightCategory =
  (typeof InsightCategory)[keyof typeof InsightCategory];

export const InsightCategory = {
  peak_hours: "peak_hours",
  session_length: "session_length",
  break_pattern: "break_pattern",
  fatigue_pattern: "fatigue_pattern",
  focus_pattern: "focus_pattern",
} as const;

export interface Insight {
  id: number;
  category: InsightCategory;
  /** Human-readable insight */
  text: string;
  /** 0-1 confidence score */
  confidence: number;
  /** Number of data points used */
  dataPoints?: number;
  generatedAt: string;
}

export interface CognitiveProfile {
  id: number;
  /** Hour of day (0-23) */
  peakFocusHourStart: number;
  peakFocusHourEnd: number;
  avgAttentionSpanMinutes: number;
  /** WPM drop % that indicates fatigue */
  fatigueThreshold: number;
  /** @nullable */
  baselineWpm?: number | null;
  /** @nullable */
  baselinePauseRate?: number | null;
  totalSessions: number;
  totalFocusMinutes: number;
  updatedAt?: string;
}

export interface ProfileUpdate {
  peakFocusHourStart?: number;
  peakFocusHourEnd?: number;
  avgAttentionSpanMinutes?: number;
  fatigueThreshold?: number;
}

export interface DashboardSummary {
  totalSessions: number;
  completedSessions: number;
  totalFocusMinutes: number;
  avgFocusScore: number;
  avgFatigueIndex: number;
  avgDistractionRisk: number;
  streakDays: number;
  todaySessions: number;
  todayFocusMinutes: number;
  /** @nullable */
  bestFocusHour?: number | null;
  totalInterventions?: number;
}

export interface TrendPoint {
  date: string;
  avgFocusScore: number;
  avgFatigueIndex: number;
  sessionCount: number;
  totalMinutes: number;
}

export interface HourlyFocusPoint {
  /** Hour of day 0-23 */
  hour: number;
  avgFocusScore: number;
  sessionCount: number;
}

export type ListSessionsParams = {
  limit?: number;
  offset?: number;
};

export type ListPredictionsParams = {
  sessionId?: number;
  limit?: number;
};

export type ListInterventionsParams = {
  sessionId?: number;
  limit?: number;
};

export type GetProductivityTrendParams = {
  days?: number;
};
