/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * NeuroFlow OS API
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
    status: string;
}
export type SessionStatus = (typeof SessionStatus)[keyof typeof SessionStatus];
export declare const SessionStatus: {
    readonly active: "active";
    readonly completed: "completed";
    readonly paused: "paused";
};
export interface Session {
    id: number;
    /** @nullable */
    label?: string | null;
    status: SessionStatus;
    startedAt: string;
    /** @nullable */
    endedAt?: string | null;
    /** @nullable */
    durationMinutes?: number | null;
    /** 0-100 average focus score for session */
    focusScore: number;
    /** 0-100 fatigue index */
    fatigueIndex: number;
    /** 0-100 distraction risk */
    distractionRisk: number;
    /**
     * Average typing speed in WPM
     * @nullable
     */
    typingWpm?: number | null;
    /**
     * Average pause frequency
     * @nullable
     */
    pauseRate?: number | null;
    /** @nullable */
    backspaceRate?: number | null;
    snapshotCount?: number;
}
export interface SessionInput {
    label?: string;
}
export type SessionUpdateStatus = (typeof SessionUpdateStatus)[keyof typeof SessionUpdateStatus];
export declare const SessionUpdateStatus: {
    readonly completed: "completed";
    readonly paused: "paused";
    readonly active: "active";
};
export interface SessionUpdate {
    status?: SessionUpdateStatus;
    label?: string;
}
export interface BehavioralSnapshot {
    id: number;
    sessionId: number;
    capturedAt: string;
    typingWpm: number;
    pauseCount: number;
    pauseDurationMs?: number;
    backspaceRate: number;
    keystrokeCount?: number;
    idleTimeMs?: number;
    focusScore: number;
    fatigueIndex: number;
    distractionRisk: number;
}
export interface SnapshotInput {
    sessionId: number;
    typingWpm: number;
    pauseCount: number;
    pauseDurationMs?: number;
    backspaceRate: number;
    keystrokeCount: number;
    idleTimeMs?: number;
}
export type PredictionFocusTrend = (typeof PredictionFocusTrend)[keyof typeof PredictionFocusTrend];
export declare const PredictionFocusTrend: {
    readonly rising: "rising";
    readonly stable: "stable";
    readonly declining: "declining";
    readonly critical: "critical";
};
export type PredictionAlertLevel = (typeof PredictionAlertLevel)[keyof typeof PredictionAlertLevel];
export declare const PredictionAlertLevel: {
    readonly none: "none";
    readonly low: "low";
    readonly medium: "medium";
    readonly high: "high";
    readonly critical: "critical";
};
export interface Prediction {
    id: number;
    sessionId: number;
    predictedAt: string;
    /** Current focus score 0-100 */
    focusScore: number;
    /** Fatigue level 0-100 */
    fatigueIndex: number;
    /** Distraction risk 0-100 */
    distractionRisk: number;
    focusTrend: PredictionFocusTrend;
    /**
     * Predicted minutes until focus drop (null if stable)
     * @nullable
     */
    minutesUntilFocusDrop?: number | null;
    alertLevel?: PredictionAlertLevel;
}
export type InterventionType = (typeof InterventionType)[keyof typeof InterventionType];
export declare const InterventionType: {
    readonly break_suggestion: "break_suggestion";
    readonly focus_mode: "focus_mode";
    readonly reduce_noise: "reduce_noise";
    readonly warning: "warning";
    readonly encouragement: "encouragement";
};
export interface Intervention {
    id: number;
    sessionId: number;
    type: InterventionType;
    message: string;
    triggeredAt: string;
    acknowledged: boolean;
    /** @nullable */
    acknowledgedAt?: string | null;
}
export interface SnapshotResult {
    snapshot: BehavioralSnapshot;
    prediction: Prediction;
    intervention?: Intervention;
}
export type InsightCategory = (typeof InsightCategory)[keyof typeof InsightCategory];
export declare const InsightCategory: {
    readonly peak_hours: "peak_hours";
    readonly session_length: "session_length";
    readonly break_pattern: "break_pattern";
    readonly fatigue_pattern: "fatigue_pattern";
    readonly focus_pattern: "focus_pattern";
};
export interface Insight {
    id: number;
    category: InsightCategory;
    /** Human-readable insight */
    text: string;
    /** 0-1 confidence score */
    confidence: number;
    /** Number of data points used */
    dataPoints?: number;
    generatedAt: string;
}
export interface CognitiveProfile {
    id: number;
    /** Hour of day (0-23) */
    peakFocusHourStart: number;
    peakFocusHourEnd: number;
    avgAttentionSpanMinutes: number;
    /** WPM drop % that indicates fatigue */
    fatigueThreshold: number;
    /** @nullable */
    baselineWpm?: number | null;
    /** @nullable */
    baselinePauseRate?: number | null;
    totalSessions: number;
    totalFocusMinutes: number;
    updatedAt?: string;
}
export interface ProfileUpdate {
    peakFocusHourStart?: number;
    peakFocusHourEnd?: number;
    avgAttentionSpanMinutes?: number;
    fatigueThreshold?: number;
}
export interface DashboardSummary {
    totalSessions: number;
    completedSessions: number;
    totalFocusMinutes: number;
    avgFocusScore: number;
    avgFatigueIndex: number;
    avgDistractionRisk: number;
    streakDays: number;
    todaySessions: number;
    todayFocusMinutes: number;
    /** @nullable */
    bestFocusHour?: number | null;
    totalInterventions?: number;
}
export interface TrendPoint {
    date: string;
    avgFocusScore: number;
    avgFatigueIndex: number;
    sessionCount: number;
    totalMinutes: number;
}
export interface HourlyFocusPoint {
    /** Hour of day 0-23 */
    hour: number;
    avgFocusScore: number;
    sessionCount: number;
}
export type ListSessionsParams = {
    limit?: number;
    offset?: number;
};
export type ListPredictionsParams = {
    sessionId?: number;
    limit?: number;
};
export type ListInterventionsParams = {
    sessionId?: number;
    limit?: number;
};
export type GetProductivityTrendParams = {
    days?: number;
};
//# sourceMappingURL=api.schemas.d.ts.map