/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * NeuroFlow OS API
 * OpenAPI spec version: 0.1.0
 */

export interface BehavioralSnapshot {
  id: number;
  sessionId: number;
  capturedAt: Date;
  typingWpm: number;
  pauseCount: number;
  pauseDurationMs?: number;
  backspaceRate: number;
  keystrokeCount?: number;
  idleTimeMs?: number;
  focusScore: number;
  fatigueIndex: number;
  distractionRisk: number;
}
