/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * NeuroFlow OS API
 * OpenAPI spec version: 0.1.0
 */
export interface CognitiveProfile {
    id: number;
    /** Hour of day (0-23) */
    peakFocusHourStart: number;
    peakFocusHourEnd: number;
    avgAttentionSpanMinutes: number;
    /** WPM drop % that indicates fatigue */
    fatigueThreshold: number;
    /** @nullable */
    baselineWpm?: number | null;
    /** @nullable */
    baselinePauseRate?: number | null;
    totalSessions: number;
    totalFocusMinutes: number;
    updatedAt?: Date;
}
//# sourceMappingURL=cognitiveProfile.d.ts.map