/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * NeuroFlow OS API
 * OpenAPI spec version: 0.1.0
 */
export interface DashboardSummary {
    totalSessions: number;
    completedSessions: number;
    totalFocusMinutes: number;
    avgFocusScore: number;
    avgFatigueIndex: number;
    avgDistractionRisk: number;
    streakDays: number;
    todaySessions: number;
    todayFocusMinutes: number;
    /** @nullable */
    bestFocusHour?: number | null;
    totalInterventions?: number;
}
//# sourceMappingURL=dashboardSummary.d.ts.map