/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * NeuroFlow OS API
 * OpenAPI spec version: 0.1.0
 */
export type GetProductivityTrendParams = {
    days?: number;
};
//# sourceMappingURL=getProductivityTrendParams.d.ts.map