/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * NeuroFlow OS API
 * OpenAPI spec version: 0.1.0
 */
import type { InsightCategory } from "./insightCategory";

export interface Insight {
  id: number;
  category: InsightCategory;
  /** Human-readable insight */
  text: string;
  /** 0-1 confidence score */
  confidence: number;
  /** Number of data points used */
  dataPoints?: number;
  generatedAt: Date;
}
