/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * NeuroFlow OS API
 * OpenAPI spec version: 0.1.0
 */
export type InsightCategory = (typeof InsightCategory)[keyof typeof InsightCategory];
export declare const InsightCategory: {
    readonly peak_hours: "peak_hours";
    readonly session_length: "session_length";
    readonly break_pattern: "break_pattern";
    readonly fatigue_pattern: "fatigue_pattern";
    readonly focus_pattern: "focus_pattern";
};
//# sourceMappingURL=insightCategory.d.ts.map