/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * NeuroFlow OS API
 * OpenAPI spec version: 0.1.0
 */

export type InsightCategory =
  (typeof InsightCategory)[keyof typeof InsightCategory];

export const InsightCategory = {
  peak_hours: "peak_hours",
  session_length: "session_length",
  break_pattern: "break_pattern",
  fatigue_pattern: "fatigue_pattern",
  focus_pattern: "focus_pattern",
} as const;
