/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * NeuroFlow OS API
 * OpenAPI spec version: 0.1.0
 */
import type { InterventionType } from "./interventionType";
export interface Intervention {
    id: number;
    sessionId: number;
    type: InterventionType;
    message: string;
    triggeredAt: Date;
    acknowledged: boolean;
    /** @nullable */
    acknowledgedAt?: Date | null;
}
//# sourceMappingURL=intervention.d.ts.map