/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * NeuroFlow OS API
 * OpenAPI spec version: 0.1.0
 */
export type InterventionType = (typeof InterventionType)[keyof typeof InterventionType];
export declare const InterventionType: {
    readonly break_suggestion: "break_suggestion";
    readonly focus_mode: "focus_mode";
    readonly reduce_noise: "reduce_noise";
    readonly warning: "warning";
    readonly encouragement: "encouragement";
};
//# sourceMappingURL=interventionType.d.ts.map