/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * NeuroFlow OS API
 * OpenAPI spec version: 0.1.0
 */

export type InterventionType =
  (typeof InterventionType)[keyof typeof InterventionType];

export const InterventionType = {
  break_suggestion: "break_suggestion",
  focus_mode: "focus_mode",
  reduce_noise: "reduce_noise",
  warning: "warning",
  encouragement: "encouragement",
} as const;
