/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * NeuroFlow OS API
 * OpenAPI spec version: 0.1.0
 */

export type PredictionFocusTrend =
  (typeof PredictionFocusTrend)[keyof typeof PredictionFocusTrend];

export const PredictionFocusTrend = {
  rising: "rising",
  stable: "stable",
  declining: "declining",
  critical: "critical",
} as const;
