/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * NeuroFlow OS API
 * OpenAPI spec version: 0.1.0
 */
export type PredictionAlertLevel = (typeof PredictionAlertLevel)[keyof typeof PredictionAlertLevel];
export declare const PredictionAlertLevel: {
    readonly none: "none";
    readonly low: "low";
    readonly medium: "medium";
    readonly high: "high";
    readonly critical: "critical";
};
//# sourceMappingURL=predictionAlertLevel.d.ts.map