/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * NeuroFlow OS API
 * OpenAPI spec version: 0.1.0
 */
export type PredictionFocusTrend = (typeof PredictionFocusTrend)[keyof typeof PredictionFocusTrend];
export declare const PredictionFocusTrend: {
    readonly rising: "rising";
    readonly stable: "stable";
    readonly declining: "declining";
    readonly critical: "critical";
};
//# sourceMappingURL=predictionFocusTrend.d.ts.map