/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * NeuroFlow OS API
 * OpenAPI spec version: 0.1.0
 */

export type PredictionAlertLevel =
  (typeof PredictionAlertLevel)[keyof typeof PredictionAlertLevel];

export const PredictionAlertLevel = {
  none: "none",
  low: "low",
  medium: "medium",
  high: "high",
  critical: "critical",
} as const;
