/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * NeuroFlow OS API
 * OpenAPI spec version: 0.1.0
 */
export interface ProfileUpdate {
    peakFocusHourStart?: number;
    peakFocusHourEnd?: number;
    avgAttentionSpanMinutes?: number;
    fatigueThreshold?: number;
}
//# sourceMappingURL=profileUpdate.d.ts.map