/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * NeuroFlow OS API
 * OpenAPI spec version: 0.1.0
 */
export type SessionUpdateStatus = (typeof SessionUpdateStatus)[keyof typeof SessionUpdateStatus];
export declare const SessionUpdateStatus: {
    readonly completed: "completed";
    readonly paused: "paused";
    readonly active: "active";
};
//# sourceMappingURL=sessionUpdateStatus.d.ts.map