/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * NeuroFlow OS API
 * OpenAPI spec version: 0.1.0
 */
import type { SessionStatus } from "./sessionStatus";
export interface Session {
    id: number;
    /** @nullable */
    label?: string | null;
    status: SessionStatus;
    startedAt: Date;
    /** @nullable */
    endedAt?: Date | null;
    /** @nullable */
    durationMinutes?: number | null;
    /** 0-100 average focus score for session */
    focusScore: number;
    /** 0-100 fatigue index */
    fatigueIndex: number;
    /** 0-100 distraction risk */
    distractionRisk: number;
    /**
     * Average typing speed in WPM
     * @nullable
     */
    typingWpm?: number | null;
    /**
     * Average pause frequency
     * @nullable
     */
    pauseRate?: number | null;
    /** @nullable */
    backspaceRate?: number | null;
    snapshotCount?: number;
}
//# sourceMappingURL=session.d.ts.map