/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * NeuroFlow OS API
 * OpenAPI spec version: 0.1.0
 */

export type SessionUpdateStatus =
  (typeof SessionUpdateStatus)[keyof typeof SessionUpdateStatus];

export const SessionUpdateStatus = {
  completed: "completed",
  paused: "paused",
  active: "active",
} as const;
