/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * NeuroFlow OS API
 * OpenAPI spec version: 0.1.0
 */
export type SessionStatus = (typeof SessionStatus)[keyof typeof SessionStatus];
export declare const SessionStatus: {
    readonly active: "active";
    readonly completed: "completed";
    readonly paused: "paused";
};
//# sourceMappingURL=sessionStatus.d.ts.map