/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * NeuroFlow OS API
 * OpenAPI spec version: 0.1.0
 */
export interface SnapshotInput {
    sessionId: number;
    typingWpm: number;
    pauseCount: number;
    pauseDurationMs?: number;
    backspaceRate: number;
    keystrokeCount: number;
    idleTimeMs?: number;
}
//# sourceMappingURL=snapshotInput.d.ts.map