/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * NeuroFlow OS API
 * OpenAPI spec version: 0.1.0
 */
import type { BehavioralSnapshot } from "./behavioralSnapshot";
import type { Intervention } from "./intervention";
import type { Prediction } from "./prediction";
export interface SnapshotResult {
    snapshot: BehavioralSnapshot;
    prediction: Prediction;
    intervention?: Intervention;
}
//# sourceMappingURL=snapshotResult.d.ts.map