/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * NeuroFlow OS API
 * OpenAPI spec version: 0.1.0
 */

export interface TrendPoint {
  date: Date;
  avgFocusScore: number;
  avgFatigueIndex: number;
  sessionCount: number;
  totalMinutes: number;
}
